First screen
laridtm/challangeNetflix pull request #1
Opened 2020-02-26 17:33 UTC by laridtm

## Descrição
Primeiro PR desse projeto trata-se do início da criação do layout da primeira tela do app, povoando a célula somente com uma imagem e arredondando as suas bordas.

### Screen

![Screen Shot 2020-02-26 at 14 32 05](https://user-images.githubusercontent.com/55598696/75370997-c454e400-58a4-11ea-9526-513f308d201c.png)

Link da issue: https://github.com/involvestecnologia/mnc-ios-movies/issues/88

2020-02-26 17:38 UTC, Raafas requested changes

2020-02-26 17:38 UTC, Raafas commented on challangeNetflix/MovieCell.swift
> +        movieImage1.image = #imageLiteral(resourceName: "malevola")
```suggestion
movieImage1.image = UIImage(named: "malevola")
```

2020-02-26 17:38 UTC, Raafas commented on challangeNetflix/MovieCell.swift
> +        movieImage1.image = #imageLiteral(resourceName: "malevola")
Desse jeito tem um problema, toda celula q tu criar vai ter a mesma imagem

2020-02-26 17:38 UTC, Raafas commented on challangeNetflix/MovieCell.swift
> +        movieImage1.layer.cornerRadius = 15
Adiciona isso dentro de um `init` pra evitar chamar toda vez q adicionar uma imagem

```swift
override init(frame: CGRect)
```

2020-02-26 17:44 UTC, laridtm commented on challangeNetflix/MovieCell.swift
> +        movieImage1.image = #imageLiteral(resourceName: "malevola")
fiz isso temporariamente enquanto nao usamos a api pra ter todos os filmes direitinho

2020-02-26 18:25 UTC, laridtm commented on challangeNetflix/MovieCell.swift
> +        movieImage1.layer.cornerRadius = 15
se eu tirar a função ele nao colocar a imagem
![Screen Shot 2020-02-26 at 15 25 04](https://user-images.githubusercontent.com/55598696/75375081-2b29cb80-58ac-11ea-991c-2f377179c218.png)

2020-02-26 18:40 UTC, Raafas requested changes

2020-02-26 18:40 UTC, Raafas commented on challangeNetflix/MovieCell.swift
> +        movieImage1.image = #imageLiteral(resourceName: "malevola")
Só vai ter uma imagem nessa celula, nao tem pq chamar de movieImage**1**

2020-02-27 16:10 UTC, Raafas requested changes

2020-02-27 16:10 UTC, Raafas commented on challangeNetflix/MovieCell.swift
> +         movieImage.image = #imageLiteral(resourceName: "malevola")
```swift
movieImage.image = UIImage(named: "malevola")
```

2020-02-27 16:34 UTC, Raafas approved these changes

2020-02-27 16:36 UTC, merged