Favorites
laridtm/challangeNetflix pull request #14
Opened 2020-03-20 21:01 UTC by laridtm

## Descrição 

* No canto superior direito da tela de detalhes há o botão ` favButton `  para marcar o filme atual como favorito. Ao clicar neste botão o filme é salvo num banco de dados de filmes favoritos. 

* Ao abrir o app, se o filme já foi favoritado, ele consta no banco e o botão ` favButton ` está preenchido, caso ele não seja favorito, não estará no banco, e o botão fica vazado.

* Ao clicar no ` favButton ` **preenchido** ele remove o filme do banco e torna a aparecer vazado.

* Ao clicar no ` favButton ` **vazado** ele adiciona o filme no banco e aparece preenchido.

* Link da issue: https://github.com/involvestecnologia/mnc-ios-movies/issues/99

### Screen 

* Marcando filme Avatar como favorito.
![Screen Shot 2020-03-20 at 17 57 25](https://user-images.githubusercontent.com/55598696/77205755-43b88a80-6ad4-11ea-87d6-ba90f66ca73c.png)

* Marcando filme Interstellar como favorito.
![Screen Shot 2020-03-20 at 17 59 18](https://user-images.githubusercontent.com/55598696/77205873-8712f900-6ad4-11ea-9835-e5018750164f.png)

* Mostrando banco de favoritos.
![Screen Shot 2020-03-20 at 17 58 12](https://user-images.githubusercontent.com/55598696/77205806-5fbc2c00-6ad4-11ea-8c79-717aa34f3b87.png)

* Desmarcando Avatar de favoritos.
![Screen Shot 2020-03-20 at 18 00 02](https://user-images.githubusercontent.com/55598696/77205917-a14cd700-6ad4-11ea-9899-c91cb7a8b0b4.png)

* Mostrando o banco novamente.
![Screen Shot 2020-03-20 at 18 00 43](https://user-images.githubusercontent.com/55598696/77205950-b9bcf180-6ad4-11ea-88e0-b860d9ffa679.png)

2020-03-23 01:45 UTC, Raafas requested changes

2020-03-23 01:45 UTC, Raafas commented on challangeNetflix/DetailsViewController.swift
> +    func deleteRealm(title: String) {
DeleteRealm parece q ta deletando o banco, pensa num nome melhor

2020-03-23 01:45 UTC, Raafas commented on challangeNetflix/DetailsViewController.swift
> +    func createRealm() {
A mesma coisa aqui, parece q ta criando o banco

2020-03-23 01:45 UTC, Raafas commented on challangeNetflix/DetailsViewController.swift
> +        movieRealm.title = self.movie!.title
force unwrap

2020-03-23 01:45 UTC, Raafas commented on challangeNetflix/DetailsViewController.swift
> +//        movieRealm.trailer = self.movie!.trailer
remove as linhas comentadas

2020-03-23 01:45 UTC, Raafas commented on challangeNetflix/MovieRealm.swift
> +//    @objc dynamic var actors = ""
Remove tudo isso comentado

2020-03-24 18:50 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        }
Como falamos na conversa, pode remover esses caras

2020-03-24 18:51 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        var isFavorite = favExist(title: movie!.title)
Pode ser let, ja que o valor não vai variar

2020-03-24 18:54 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        }
```suggestion
  markButton.image = UIImage(named: isFavorite ? "marked" : "mark") 
```

2020-03-24 18:55 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        let realm = try! Realm()
Adicionar do { }

2020-03-24 18:55 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        }
```suggestion
        return objects.count > 0
```

2020-03-24 18:56 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        let realm = try! Realm()
Adicionar do { }

2020-03-24 18:57 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +        do {
Vai ter que adicionar um let realm = try? Realm()

2020-03-24 18:57 UTC, giovanepossebon commented on challangeNetflix/Movie.swift
> +class Movie: Codable {
Por que não Struct?

2020-03-24 18:58 UTC, giovanepossebon commented on challangeNetflix/Movie.swift
> +    required init(from Decoder: Decoder) throws {
É necessario esse init?

2020-03-25 20:31 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +            let realm = try! Realm()
Não precisa do `!` ja que tu ta fazendo dentro de um `do`

2020-03-25 20:32 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +            let realm = try! Realm()
Mesma coisa aqui

2020-03-25 20:32 UTC, giovanepossebon commented on challangeNetflix/DetailsViewController.swift
> +            do {
Acho que não precisa de dois `do`, acho que tu pode fazer dentro do mesmo

2020-03-25 20:36 UTC, giovanepossebon approved these changes

2020-03-25 20:39 UTC, merged